config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contracts.urls', namespace='contracts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('limits.urls', namespace='limits')),
    path('lib_ccportal/', include('lib_ccportal.urls')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contracts/urls.py
from django.urls import path

from contracts.views import PurchaseListView, IndexView, AddContractView, AddPaymentDocView, AddPaymentOrderView, \
    JournalListView, AddAdditionalAgreementView, ContractDetailView, ExportToExcelView, ContractEditView, \
    ContractDeleteView, AdditionalAgreementDetailView

app_name = 'contracts'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contracts/', PurchaseListView.as_view(), name='purchase_list'),
    path('contracts/journal', JournalListView.as_view(), name='journal_list'),
    path('add/', AddContractView.as_view(), name='add_contract'),
    path('contract/<int:pk>/', ContractDetailView.as_view(), name='contract-detail'),
    path('contract/<int:contract_id>/edit/', ContractEditView.as_view(), name='contract-edit'),
    path('contract/<int:pk>/delete/', ContractDeleteView.as_view(), name='contract-delete'),
    path('contract/<int:contract_id>/add_doc', AddPaymentDocView.as_view(), name='add_payment_doc'),
    path('contract/<int:contract_id>/add_order', AddPaymentOrderView.as_view(), name='add_payment_order'),
    path('export-excel/', ExportToExcelView.as_view(), name='export_excel'),
    path('contract/<int:contract_id>/add_agreement/', AddAdditionalAgreementView.as_view(), name='add_additional_agreement'),
    path('contract/<int:contract_id>/additional_agreement/<int:pk>/', AdditionalAgreementDetailView.as_view(), name='additional-agreement-detail'),
]

limits/urls.py
from django.urls import path
from limits.views import AddLimitView, LimitListView, CardLimitView

app_name = 'limits'

urlpatterns = [
    path('limits-list/', LimitListView.as_view(), name='limits_list'),
    path('add-limit/', AddLimitView.as_view(), name='add_limit'),
    path('card_limit/<path:kbk>/<int:kosgu>/<int:year>/', CardLimitView.as_view(), name='card_limit')
]

users/urls.py
from django.urls import path

from users.views import CustomLoginView

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
]

limits/models.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

from lib_ccportal.models import KBK, KOSGU


# Create your models here.
class Limit(models.Model):
    name = models.CharField(max_length=300)
    kbk = models.ForeignKey(KBK, on_delete=models.PROTECT, related_name='limits')
    kosgu = models.ForeignKey(KOSGU, on_delete=models.PROTECT, related_name='limits')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    remaining_limit = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    year = models.PositiveIntegerField(default=datetime.datetime.now().year)

    def __str__(self):
        return self.name


# Сигнал для обновления остатка лимита при создании контракта
@receiver(post_save, sender='contracts.Contract')
def update_remaining_limit(sender, instance, created, **kwargs):
    if created:
        try:
            limit = Limit.objects.get(
                kbk=instance.kbk_type,
                kosgu=instance.kosgu_type,
                year=instance.contract_date.year
            )
            limit.remaining_limit -= instance.contract_amount
            limit.save(update_fields=['remaining_limit'])
        except Limit.DoesNotExist:
            pass

# Сигнал для проверки превышения лимита при сохранении контракта
@receiver(pre_save, sender='contracts.Contract')
def check_limit_exceeded(sender, instance, **kwargs):
    try:
        limit = Limit.objects.get(
            kbk=instance.kbk_type,
            kosgu=instance.kosgu_type,
            year=instance.contract_date.year
        )
        if instance.contract_amount > limit.remaining_limit:
            raise ValidationError("Превышен лимит финансирования.")
    except Limit.DoesNotExist:
        pass

limits/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from lib_ccportal.models import KBK, KOSGU, PurchaseObject
from limits.models import Limit


class LimitForm(forms.ModelForm):
    name = forms.ChoiceField(  # Используем ChoiceField для наименования объекта закупки
        choices=[],  # Сначала оставляем пустым
        label=_("Наименование объекта закупки")
    )

    kbk = forms.ModelChoiceField(
        queryset=KBK.objects.all(),
        label=_("КБК")
    )

    kosgu = forms.ModelChoiceField(
        queryset=KOSGU.objects.all(),
        label=_("КОСГУ")
    )

    amount = forms.DecimalField(label=_("Сумма доведенных лимитов"))

    class Meta:
        model = Limit  # Указываем модель, с которой работает форма
        fields = ['name', 'kbk', 'kosgu', 'amount']  # Указываем поля, которые будут включены в форму

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Заполняем choices для поля name на основе данных из модели PurchaseObject
        self.fields['name'].choices = [(purchase.code, purchase.description) for purchase in
                                       PurchaseObject.objects.all()]
    def clean(self):
        cleaned_data = super().clean()
        kbk_code = cleaned_data.get("kbk")
        kosgu_code = cleaned_data.get("kosgu")

        if kbk_code:
            try:
                cleaned_data['kbk'] = KBK.objects.get(code=kbk_code)
            except KBK.DoesNotExist:
                self.add_error('kbk', _("Выбранный КБК не существует."))

        if kosgu_code:
            try:
                cleaned_data['kosgu'] = KOSGU.objects.get(code=kosgu_code)
            except KOSGU.DoesNotExist:
                self.add_error('kosgu', _("Выбранный КОСГУ не существует."))

        return cleaned_data

limits/views.py
from datetime import datetime
from decimal import Decimal

from django.contrib import messages
from django.db import models
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, TemplateView

from contracts.models import Contract
from lib_ccportal.models import PurchaseObject, KBK, KOSGU
from .forms import LimitForm
from .models import Limit


class LimitListView(ListView):
    model = Limit
    template_name = 'limits/limits_list.html'
    context_object_name = 'limits'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        summary = []

        for limit in context['limits']:
            # Фильтрация контрактов по КБК, КОСГУ и году
            contracts = Contract.objects.filter(
                kbk_type=limit.kbk,
                kosgu_type=limit.kosgu,
                contract_date__year=limit.year
            )

            # Сумма цен контрактов
            total_contract_amount = contracts.aggregate(total=models.Sum('contract_amount'))['total'] or Decimal('0.00')

            # Остаток по лимиту
            remaining_amount = Decimal(limit.amount) - total_contract_amount

            summary.append({
                'kbk': limit.kbk,
                'kosgu': limit.kosgu,
                'year': limit.year,
                'amount': limit.amount,
                'total_contract_amount': total_contract_amount,
                'remaining_amount': remaining_amount,
            })

        # Передаем в контекст
        context['summary'] = summary
        context['page_title'] = 'Доведенные лимиты'
        context['PURCHASE_ODJ_CHOICE'] = PurchaseObject

        return context

class AddLimitView(CreateView):
    model = Limit
    form_class = LimitForm
    template_name = 'limits/add_limit.html'
    success_url = reverse_lazy('limits:limits_list')

    def form_valid(self, form):
        print(form.cleaned_data)
        limit = form.save(commit=False)
        limit.save()
        messages.success(self.request, 'Лимит успешно создан!')
        return HttpResponseRedirect(self.success_url)

class UpdateLimitView(UpdateView):
    model = Limit
    form_class = LimitForm
    template_name = 'limits/update_limit.html'
    success_url = reverse_lazy('limits:limits_list')

    def form_valid(self, form):
        limit = form.save(commit=False)
        print(limit.kbk, limit.kosgu)
        limit.save()
        messages.success(self.request, 'Лимит успешно изменен!')
        return HttpResponseRedirect(self.success_url)

class DeleteLimitView(DeleteView):
    model = Limit
    success_url = reverse_lazy('limits:limits_list')

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Лимит удалён.')
        return super().delete(*args, **kwargs)


def get_kbk_value(kbk):
    try:
        return next(choice for choice in KBK.objects.all() if choice.code == kbk)  # Верно
    except StopIteration:
        return None

def get_kosgu_value(kosgu):
    try:
        return next(choice for choice in KOSGU.objects.all() if choice.code == str(kosgu))
    except StopIteration:
        return None


class CardLimitView(TemplateView):
    template_name = 'limits/card_limit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        kbk = self.kwargs['kbk']
        kosgu = str(self.kwargs['kosgu'])  # Приведение к строке
        year = self.kwargs['year']

        kbk_value = get_kbk_value(kbk)
        kosgu_value = get_kosgu_value(kosgu)

        # Отладочная информация
        print(f"Запрашиваемый КБК: {kbk}, полученный КБК: {kbk_value}")
        print(f"Запрашиваемый КОСГУ: {kosgu}, полученный КОСГУ: {kosgu_value}")
        print(f"Запрашиваемый год: {year}")
        # Поиск лимитов по КБК, КОСГУ и году
        limit = Limit.objects.filter(kbk__code=kbk_value, kosgu__code=kosgu_value, year=year).first()

        # Если нужно работать с одним лимитом:
        if limit:
            # Получаем первый и последний дни текущего года
            start_of_current_year = datetime(year, 1, 1)
            end_of_current_year = datetime(year, 12, 31)

            # Подсчет контрактов, соответствующих фильтрам
            contracts = Contract.objects.filter(
                kbk_type=limit.kbk,
                kosgu_type=limit.kosgu,
                contract_date__range=(start_of_current_year, end_of_current_year)
            ).distinct()

            # Также добавим контракты из декабря предыдущего года
            contracts |= Contract.objects.filter(
                kbk_type=kbk_value,
                kosgu_type=kosgu_value,
                contract_date__month=12,
                contract_date__year=year - 1
            ).distinct()

            # Расчет необходимых сумм
            total_limit_amount = limit.amount if limit else 0
            total_contract_amount = contracts.aggregate(total=models.Sum('contract_amount'))['total'] or 0.00
            total_contract_amount = Decimal(total_contract_amount)  # Приведение к Decimal

            # Рассчитываем остаток
            remaining_amount = total_limit_amount - total_contract_amount

            # Флаг для превышения лимита
            limit_exceeded = total_contract_amount > total_limit_amount

            print(f"Найдено контрактов: {contracts.count()}")

            # Подготовим контекст для шаблона
            context['contracts'] = contracts
            context['kbk'] = kbk
            context['kosgu'] = kosgu
            context['year'] = year
            context['total_limit_amount'] = total_limit_amount
            context['total_contract_amount'] = total_contract_amount
            context['remaining_amount'] = remaining_amount
            context['limit_exceeded'] = limit_exceeded

        else:
            context['contracts'] = []  # Пустой список, если лимит не найден

        return context

limits/templates/limits/add_limit.html
{% extends 'contracts/base.html' %}

{% block title %}
    <title>Добавление данных о доведенных лимитах</title>
{% endblock %}

{% block page_header %}
    <h1>Добавление данных о доведенных лимитах</h1>
{% endblock %}

{% block page_content %}
<div class="add_form">
       <form method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit">Save</button>
       </form>
   </div>
{% endblock %}

limits/templates/limits/card_limit.html
{% extends 'contracts/base.html' %}

{% block title %}
    <title>Контракты по КБК/КОСГУ</title>
{% endblock %}

{% block page_header %}
    <h1>Контракты с КБК {{ kbk }} и КОСГУ {{ kosgu }}</h1>
{% endblock %}

{% block page_content %}
    <div class="summary">
        <p>Общая сумма доведенного лимита: <strong>{{ total_limit_amount }}</strong></p>
        <p>Сумма контрактов: <strong>{{ total_contract_amount }}</strong></p>
        <p>Остаток по КБК и КОСГУ: <strong>{{ remaining_amount }}</strong></p>
    </div>

    {% if limit_exceeded %}
        <div class="alert alert-danger">
            <strong>Превышение доведенного лимита по КБК и КОСГУ!</strong>
        </div>
    {% endif %}

    <div class="contract-list">
        {% if contracts %}
            <table class="contract-table" border="1" cellpadding="2" cellspacing="0">
                <thead>
                    <tr>
                        <th>Контрагент</th>
                        <th>Предмет контракта</th>
                        <th>Номер контракта</th>
                        <th>Дата заключения контракта</th>
                        <th>Срок действия контракта</th>
                        <th>Сумма Контракта</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contract in contracts %}
                    <tr>
                        <td>{{ contract.supplier }}</td>
                        <td>{{ contract.contract_subject }}</td>
                        <td><a href="{% url 'contracts:contract-detail' contract.id %}">{{ contract.contract_number }}</a></td>
                        <td>{{ contract.contract_date|date:"d.m.Y" }}</td>
                        <td>{{ contract.service_start_date|date:"d.m.Y" }} -  {{ contract.service_end_date|date:"d.m.Y" }}</td>
                        <td>{{ contract.contract_amount }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="6">Контрактов с такими параметрами нет. Проверьте КБК: {{ kbk }} и КОСГУ: {{ kosgu }}.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Контрактов с такими параметрами нет.</p>
        {% endif %}
    </div>
{% endblock %}

limits/templates/limits/limits_list.html
{% extends 'contracts/base.html' %}

{% block title %}
    <title>{{ page_title|title }}</title>
{% endblock %}

{% block page_header %}
    <h1>Информация о доведенных лимитах</h1>
{% endblock %}

{% block page_content %}
    {% if user.is_authenticated %}
    <div class="button_container">
        <a class="pp_button" href="{% url 'limits:add_limit' %}">Добавить</a>
    </div>
    {% endif %}
    <hr>
    <table>
        <thead>
            <tr>
                <th>Год</th>
                <th>Наименование объекта закупки</th>
                <th>КБК / КОСГУ</th>
                <th>Сумма доведенного лимита</th>
                <th>Законтрактовано</th>
                <th>Остаток</th>
            </tr>
        </thead>
        <tbody>
            {% for item in summary %}
            <tr>
                <td>{{ item.year }}</td>
                <td>
                    {% for key, value in PURCHASE_ODJ_CHOICE.items %}
                        {% if key == item.kbk.code %}
                            {{ key }} / {{ value }}
                        {% endif %}
                    {% empty %}
                        Нет информации
                    {% endfor %}
                </td>
                <td><a href="{% url 'limits:card_limit' kbk=item.kbk.code kosgu=item.kosgu.code year=item.year %}">{{ item.kbk.code }} / {{ item.kosgu.code }}</a></td>
                <td>{{ item.amount }}</td>
                <td>{{ item.total_contract_amount }}</td>
                <td>{{ item.remaining_amount }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">Нет данных о лимитах.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

limits/templates/limits/update_limit.html
{% extends 'contracts/base.html' %}

{% block title %}
    <title>Добавление данных о доведенных лимитах</title>
{% endblock %}

{% block page_header %}
    <h1>Добавление данных о доведенных лимитах</h1>
{% endblock %}

{% block page_content %}
<div class="add_form">
       <form method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit">Save</button>
       </form>
   </div>
{% endblock %}